### ISSUE TITLE
Can we add text below the icon in the non-selected tabs

### ISSUE THREAD

**Issue by vinay-zorang** [susonthapa/curved-bottom-navigation#10]
How to add text below the non-selected tabs. I really need this feature and I believe it is useful for others as well.

**Comment by susonthapa** [comment]
For this we might have to change many things in the library (like making sure the text is not obstructed by the curve). So this feature will not be implemented for now, sorry.

**Comment by NadeemRawther** [comment]
> For this we might have to change many things in the library (like making sure the text is not obstructed by the curve). So this feature will not be implemented for now, sorry.

Can i add floating action button with speed dial

**Comment by susonthapa** [comment]
Sorry @NadeemRawther I didn't get your question. Can you please explain it.

**Comment by NadeemRawther** [comment]
> 
> 
> Sorry @NadeemRawther I didn't get your question. Can you please explain it.

I mean can i add a button button like  
![bottomnav](https://user-images.githubusercontent.com/17871801/131244368-f4893e3c-da44-481a-bfca-351a4b59c9ce.png)
i want to add this kind of button on bottom navigation

**Comment by susonthapa** [comment]
This is not currently supported but if you want you can fork and implement it.

**Comment by Masoudmjm** [comment]
I think this is really important to add text below the non-selected tabs. it is a beautiful bottom navigation and could be very useful

**Comment by susonthapa** [comment]
I have thought about this and other people have requested this feature as well. But there are some technical challenges that need to be tackled. Handling text in this case is quite tricky. I will do some research and see if this can be done.
