### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by Ant-Adis** [susonthapa/curved-bottom-navigation#11]
When I try to rebuild the app I get this error:

Could not GET 'https://dl.bintray.com/susonthapa/curved-bottom-navigation/np/com/susanthapa/curved_bottom_navigation/curved_bottom_navigation/0.6.3/curved_bottom_navigation-0.6.3.pom'. Received status code 403 from server: Forbidden

**Comment by Ant-Adis** [comment]
It works now

**Comment by mikesabino** [comment]
Hi we're also using this, and currently getting 403 forbidden error like above. Any idea whats causing this?

**Comment by Ant-Adis** [comment]
> Hi we're also using this, and currently getting 403 forbidden error like above. Any idea whats causing this?

Try this one:

implementation 'np.com.susanthapa:curved_bottom_navigation:0.6.5'
