### ISSUE TITLE
Curve the edge up

### ISSUE THREAD

**Issue by mrHerintsoaHasina** [susonthapa/curved-bottom-navigation#2]
Great job for your library. I'm asking if it supports a curved edge to up like seen here [bottom-navigation-round-selector](https://stackoverflow.com/questions/60399298/custom-bottom-navigation-library-round-selector). Otherwise, it's a possible enhancement to add.

**Comment by susonthapa** [comment]
Currently it doesn't support this. I think it would be over work to implement these types of different views in a single library. If you need such type of navigation you can customize this library and implement to fit your own needs. I have written a blog about this library which should get you started.
