### ISSUE TITLE
Lag when switching tabs

### ISSUE THREAD

**Issue by Masoudmjm** [susonthapa/curved-bottom-navigation#20]
when I touch a menu to change fragment , bottom navigation animation lags.
it work properly if destination fragment is empty

**Comment by susonthapa** [comment]
Can you verify if this behavior exists in other bottom navigation libraries? Most of the time, this might be the issue with the fragment itself.

**Comment by JahangirJadi** [comment]
Same issue with me. It's lagging when switching the menu.

**Comment by susonthapa** [comment]
Can you please post a video of it?

**Comment by susonthapa** [comment]
No response, closing.
