### ISSUE TITLE
ClassCastException while passing menuItems to setMenuItems() method

### ISSUE THREAD

**Issue by hpcreator** [susonthapa/curved-bottom-navigation#21]
Throwing below exception with message: 
Unable to start activity ComponentInfo{com.arika/com.arika.TestActivity}: java.lang.ClassCastException: android.graphics.drawable.BitmapDrawable cannot be cast to android.graphics.drawable.AnimatedVectorDrawable

it is not casting properly for animatedDrawables.

**Comment by susonthapa** [comment]
You are passing BitmapDrawable which is not AVD. Please look into this issue #4

**Comment by hpcreator** [comment]
Thank you for your suggestion.
I will try with that.
