### ISSUE TITLE
No avd icon

### ISSUE THREAD

**Issue by GOHILCHIRAG** [susonthapa/curved-bottom-navigation#4]
Great library and work. I would like to know how to use this library without animated icons(only simple drawable icons) in CbnMenuItem?

**Comment by susonthapa** [comment]
This is not currently possible. As a work around you can just convert any icon to animated vector drawable and use that for now.

**Comment by GOHILCHIRAG** [comment]
> 
> 
> This is not currently possible. As a work around you can just convert any icon to animated vector drawable and use that for now.

What changes we should make to do so? Can you help me in that?

**Comment by susonthapa** [comment]
You can go to [shape shifter](https://shapeshifter.design/) and upload your icon there and then just export it without adding any animations. I think that should do the trick.

**Comment by susonthapa** [comment]
I think I would try to add this option.
