### ISSUE TITLE
setOnMenuItemClickListener to trigger when clicking the selected item

### ISSUE THREAD

**Issue by fiote** [susonthapa/curved-bottom-navigation#5]
After all, the method is named "CLICK"listener, and not "CHANGE"listener, lol.

Could you change that behavior? I probably can change it myself and send a PR, tho, if you would be willing to accept.

**Comment by susonthapa** [comment]
Yeah that makes sense. You can create the PR and I will merge it

**Comment by fiote** [comment]
@susonthapa already did it, lol. Btw thanks for your work on this. Looks (and works) SOOO good!

**Comment by susonthapa** [comment]
Moving the listener to top would crash the app. I will fix.
